name: Android CI_

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    if: ${{ !startsWith(github.event.head_commit.message, '[skip ci]') }}
    steps:
      - uses: actions/checkout@v4
      - name: Setup JDK 17
        uses: actions/setup-java@v4.7.0
        with:
          distribution: 'temurin'
          java-version: 17
          cache: 'gradle'
      - name: Cache Gradle Dependencies
        uses: actions/cache@v4.2.0
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
            !~/.gradle/caches/build-cache-*
          key: gradle-deps-core-${{ hashFiles('**/build.gradle.kts') }}
          restore-keys: |
            gradle-deps
      - name: Cache Gradle Build
        uses: actions/cache@v4.2.0
        with:
          path: |
            ~/.gradle/caches/build-cache-*
            ~/.gradle/buildOutputCleanup/cache.properties
          key: gradle-builds-core-${{ github.sha }}
          restore-keys: |
            gradle-builds
      - name: Build with Gradle
#        env:
#          REL_KEY: ${{ secrets.REL_KEY }}
#          APP_SECRET: ${{ secrets.APP_SECRET }}
        run: |
          bash ./gradlew assembleDebug
      - name: Upload built apk
        if: success()
        uses: actions/upload-artifact@v4.6.0
        with:
          name: snapshot
          path: |
            ${{ github.workspace }}/app/build/outputs/apk
#            ${{ github.workspace }}/app/build/outputs/mapping
